# Generated by Django 3.0.1 on 2024-10-13 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True)),
                ('Abbreviation', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Rating', models.FloatField(default=0)),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangos.Country')),
            ],
        ),
    ]
