# Generated by Django 3.0.1 on 2024-10-13 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='Abbreviation',
            new_name='abbreviation',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mango',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='mango',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mango',
            old_name='Rating',
            new_name='rating',
        ),
    ]
